In [1]:
import pandas as pd
import json
import re

df = pd.read_csv("cleaned_articles.csv")
print(df.shape)
print(df.columns.tolist())
df.head(2)

(805, 15)
['article_id', 'title', 'content', 'text', 'published_at', 'author', 'url', 'source', 'source_country', 'language', 'raw_category', 'pre_extracted_orgs', 'pre_extracted_persons', 'pre_extracted_locations', 'content_word_count']

,article_id,title,content,text,published_at,author,url,source,source_country,language,raw_category,pre_extracted_orgs,pre_extracted_persons,pre_extracted_locations,content_word_count
0,a709ab47e525f2cc55d5b84d6fa989747d94b3d9,"Why Fannie Mae, Freddie Mac, and Redfin Soared...",Shares of Federal National Mortgage Associatio...,"Why Fannie Mae, Freddie Mac, and Redfin Soared...",2023-12-28T00:00:00Z,Steve Symington,https://www.fool.com/investing/2023/12/28/why-...,fool.com,US,english,"['Economy, Business and Finance']",[{'name': 'motley fool shares of federal natio...,"[{'name': 'freddie mac', 'sentiment': 'negativ...",[],628
1,a0fa852bab25f869c478d474a52997485960c3ba,Should You Buy Enbridge Stock for its 7.65% Yi...,Pipeline Most investors are aware of how lucra...,Should You Buy Enbridge Stock for its 7.65% Yi...,2023-12-28T22:06:00Z,VNExplorer,https://vnexplorer.net/should-you-buy-enbridge...,vnexplorer.net,US,english,"['Economy, Business and Finance']","[{'name': 'enbridge', 'sentiment': 'neutral'}]",[],"[{'name': 'united states', 'sentiment': 'none'}]",629

In [2]:
label_df = df[["article_id", "title", "content"]].copy()
print(label_df.shape)
label_df.head(2)

(805, 3)

,article_id,title,content
0,a709ab47e525f2cc55d5b84d6fa989747d94b3d9,"Why Fannie Mae, Freddie Mac, and Redfin Soared...",Shares of Federal National Mortgage Associatio...
1,a0fa852bab25f869c478d474a52997485960c3ba,Should You Buy Enbridge Stock for its 7.65% Yi...,Pipeline Most investors are aware of how lucra...

In [3]:
def truncate_text(text, max_chars=1800):
    text = str(text)
    return text[:max_chars]

label_df["label_input"] = (
    "Title: " + label_df["title"].fillna("").astype(str) +
    "\n\nContent: " + label_df["content"].fillna("").astype(str).apply(truncate_text)
)

label_df[["article_id", "label_input"]].head(1)

,article_id,label_input
0,a709ab47e525f2cc55d5b84d6fa989747d94b3d9,"Title: Why Fannie Mae, Freddie Mac, and Redfin..."

In [24]:
MACRO_TAGS = [
    "inflation",
    "interest_rates",
    "mortgage_interest_rates",
    "monetary_policy",
    "fiscal_policy",
    "recession_growth",
    "regulation",
    "fx_currency",
    "commodities",
    "geopolitics"
]
INDUSTRY_TAGS = [
    "banking",
    "insurance",
    "real_estate",
    "financials",
    "technology",
    "energy",
    "health_care",
    "industrials",
    "consumer",
    "materials",
    "utilities",
    "communication_services"
]

In [45]:
PROMPT_TEMPLATE = """
You are labeling financial news articles.

Return JSON only:
{{
  "macro_tags": [],
  "industry_tags": [],
  "entity_tags": []
}}

Rules:
- macro_tags must be chosen only from this list:
  {macro_tags}
- industry_tags must be chosen only from this list:
  {industry_tags}
- entity_tags should contain named companies, banks, regulators, funds, government bodies, or organizations explicitly mentioned in the article.
- Use lowercase snake_case for macro_tags and industry_tags.
- Keep entity_tags in normal readable names.
- Do not include explanations.
- Do not include any text before or after the JSON.
- If no tag applies, return an empty list for that field.

Article:
{article}
"""

In [11]:
def build_prompt(article_text):
    return PROMPT_TEMPLATE.format(
        macro_tags=", ".join(MACRO_TAGS),
        industry_tags=", ".join(INDUSTRY_TAGS),
        article=article_text
    )

In [12]:
sample_prompt = build_prompt(label_df.iloc[0]["label_input"])
print(sample_prompt[:3000])

You are labeling financial news articles.

Return valid JSON only with this exact schema:
{
  "macro_tags": [],
  "industry_tags": [],
  "entity_tags": []
}

Rules:
- macro_tags must be chosen only from this list:
  inflation, interest_rates, monetary_policy, fiscal_policy, recession_growth, regulation, fx_currency, commodities, geopolitics

- industry_tags must be chosen only from this list:
  banking, insurance, real_estate, financials, technology, energy, health_care, industrials, consumer, materials, utilities, communication_services

- entity_tags should contain named companies, banks, regulators, funds, government bodies, or organizations explicitly mentioned in the article.
- Use lowercase snake_case for macro_tags and industry_tags.
- Keep entity_tags in normal readable names.
- Do not include explanations.
- Do not include any text before or after the JSON.
- If no tag applies, return an empty list for that field.

Article:
Title: Why Fannie Mae, Freddie Mac, and Redfin Soared This Week | The Motley Fool

Content: Shares of Federal National Mortgage Association ( FNMA 6.80% ) , also known as Fannie Mae, are up 11.6% this week as of Thursday's close, according to data provided by S&P Global Market Intelligence . Federal Home Loan Mortgage Corp ( FMCC 5.51% ) , also known as Freddie Mac, and online real estate platform Redfin (NASDAQ: RDFN) are also each up more than 9% this week as of this writing. Their catalyst in common: Lower mortgage-interest rates are bolstering home affordability, mortgage activity, and new home listings. Mortgage applications and new listings are surging In a press release last week, Fannie Mae's Economic and Strategic Research (ESR) Group predicted a "mild economic downturn" in 2024, "including stretched consumer spending relative to personal incomes and the continued effects of restrictive monetary policy still working through the economy." But the group also forecasts a return to growth in 2025. Thanks to a sharp decline in mortgage- interest rates in recent weeks, mortgage applications have already rebounded roughly 15% from their trough in November. Fannie Mae added that it expects this trend to continue if mortgage rates keep falling. Indeed, according to data released earlier today by Freddie Mac, the average mortgage rate for a 30-year fixed-rate loan declined to 6.61% this week, marking its lowest level since May. This was also the ninth straight week of declines since mortgage-interest rates hit their highest level in 22 years in late October. Meanwhile, according to Redfin last week, those interest-rate declines have already resulted in a double-digit percent increase in homeowners contacting real estate agents for help in selling their homes. Redfin added that new listings also promptly climbed 9% year over year, good for the highest annual bum

In [13]:
import requests

In [14]:
OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "mistral:latest"

In [15]:
def call_ollama(prompt, model=MODEL_NAME):
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False
    }
    
    response = requests.post(OLLAMA_URL, json=payload)
    response.raise_for_status()
    
    data = response.json()
    return data["response"]

In [16]:
raw_output = call_ollama(sample_prompt)
print(raw_output)

 {
  "macro_tags": ["mortgage_interest_rates", "monetary_policy"],
  "industry_tags": ["financials", "real_estate"],
  "entity_tags": ["Fannie Mae", "Freddie Mac", "Redfin"]
}

In [19]:
import json
import re

In [20]:
def extract_json_object(text):
    text = str(text).strip()
    
    # Try direct JSON parse first
    try:
        return json.loads(text)
    except:
        pass
    
    # If model adds extra text, try to recover the JSON block
    match = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if match:
        try:
            return json.loads(match.group(0))
        except:
            pass
    
    # Fallback
    return {
        "macro_tags": [],
        "industry_tags": [],
        "entity_tags": [],
        "parse_error": True,
        "raw_output": text
    }

In [26]:
parsed_output = extract_json_object(raw_output)
parsed_output

{'macro_tags': ['consumer'],
 'industry_tags': ['technology'],
 'entity_tags': ['apple', 'bh_photo_video']}

In [22]:
def normalize_labels(result):
    if not isinstance(result, dict):
        result = {}
    
    macro_tags = result.get("macro_tags", [])
    industry_tags = result.get("industry_tags", [])
    entity_tags = result.get("entity_tags", [])
    
    if not isinstance(macro_tags, list):
        macro_tags = []
    if not isinstance(industry_tags, list):
        industry_tags = []
    if not isinstance(entity_tags, list):
        entity_tags = []
    
    # keep only allowed macro and industry tags
    macro_tags = [x for x in macro_tags if x in MACRO_TAGS]
    industry_tags = [x for x in industry_tags if x in INDUSTRY_TAGS]
    
    # clean entity tags
    entity_tags = [str(x).strip() for x in entity_tags if str(x).strip()]
    
    # remove duplicates while preserving order
    macro_tags = list(dict.fromkeys(macro_tags))
    industry_tags = list(dict.fromkeys(industry_tags))
    entity_tags = list(dict.fromkeys(entity_tags))
    
    return {
        "macro_tags": macro_tags,
        "industry_tags": industry_tags,
        "entity_tags": entity_tags
    }

In [25]:
normalized_output = normalize_labels(parsed_output)
normalized_output

{'macro_tags': [],
 'industry_tags': ['technology'],
 'entity_tags': ['apple', 'bh_photo_video']}

In [28]:
macro_tags = normalized_output["macro_tags"]
industry_tags = normalized_output["industry_tags"]
entity_tags = normalized_output["entity_tags"]

print("Macro:", macro_tags)
print("Industry:", industry_tags)
print("Entity:", entity_tags)

Macro: []
Industry: ['technology']
Entity: ['apple', 'bh_photo_video']

In [29]:
#5 articles test
test_5 = label_df.sample(5, random_state=42).copy()
test_5["prompt"] = test_5["label_input"].apply(build_prompt)

print(test_5.shape)
test_5[["article_id", "title"]]

(5, 5)

,article_id,title
192,5bce820b060ef08e7f276f84c3406ec08c6311b5,Apple's New M3 Pro MacBook Pro Gets an Epic $3...
718,64983ee8c7ac596bcf012bc57e4466c160ebbc2c,Rossen Reports: Secret ways to save money at t...
168,83d8c1441e7ac5f0ca6653117311f001e18b502c,Applied Intuition Announces Favorable Resoluti...
522,2f8f94ab60b08cbb48c6a4ee55aa02b8db901de8,"Foreign investors return, stock market rebound..."
536,66f04e86ca2e659b12fef67f266755047efbc8df,Ground News - Sudbury's hospital draw Friday w...

In [30]:
results = []

for i, (_, row) in enumerate(test_5.iterrows(), start=1):
    print(f"Processing article {i}/5...")
    
    raw_output = call_ollama(row["prompt"])
    parsed_output = extract_json_object(raw_output)
    normalized_output = normalize_labels(parsed_output)
    
    results.append({
        "article_id": row["article_id"],
        "title": row["title"],
        "raw_output": raw_output,
        "macro_tags": normalized_output["macro_tags"],
        "industry_tags": normalized_output["industry_tags"],
        "entity_tags": normalized_output["entity_tags"]
    })

Processing article 1/5...
Processing article 2/5...
Processing article 3/5...
Processing article 4/5...
Processing article 5/5...

In [31]:
results_df = pd.DataFrame(results)
results_df

,article_id,title,raw_output,macro_tags,industry_tags,entity_tags
0,5bce820b060ef08e7f276f84c3406ec08c6311b5,Apple's New M3 Pro MacBook Pro Gets an Epic $3...,"{\n ""macro_tags"": [""technology""],\n ""indust...",[],"[consumer, financials]",[apple]
1,64983ee8c7ac596bcf012bc57e4466c160ebbc2c,Rossen Reports: Secret ways to save money at t...,"{\n ""macro_tags"": [""inflation""],\n ""industr...",[inflation],[],"[AMC, Cinemark, Regal Cinemas, Alamo Megaplex,..."
2,83d8c1441e7ac5f0ca6653117311f001e18b502c,Applied Intuition Announces Favorable Resoluti...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[technology],"[Applied Intuition, Embark Technology, Marceil..."
3,2f8f94ab60b08cbb48c6a4ee55aa02b8db901de8,"Foreign investors return, stock market rebound...","{\n ""macro_tags"": [""none""],\n ""industry_tag...",[],[],[]
4,66f04e86ca2e659b12fef67f266755047efbc8df,Ground News - Sudbury's hospital draw Friday w...,"{\n ""macro_tags"": [""geopolitics""],\n ""indus...",[geopolitics],[health_care],"[Leon Cooperman, Allianz]"

In [32]:
test_5_labeled = test_5.merge(
    results_df[["article_id", "macro_tags", "industry_tags", "entity_tags"]],
    on="article_id",
    how="left"
)

test_5_labeled[["article_id", "title", "macro_tags", "industry_tags", "entity_tags"]]

,article_id,title,macro_tags,industry_tags,entity_tags
0,5bce820b060ef08e7f276f84c3406ec08c6311b5,Apple's New M3 Pro MacBook Pro Gets an Epic $3...,[],"[consumer, financials]",[apple]
1,64983ee8c7ac596bcf012bc57e4466c160ebbc2c,Rossen Reports: Secret ways to save money at t...,[inflation],[],"[AMC, Cinemark, Regal Cinemas, Alamo Megaplex,..."
2,83d8c1441e7ac5f0ca6653117311f001e18b502c,Applied Intuition Announces Favorable Resoluti...,[],[technology],"[Applied Intuition, Embark Technology, Marceil..."
3,2f8f94ab60b08cbb48c6a4ee55aa02b8db901de8,"Foreign investors return, stock market rebound...",[],[],[]
4,66f04e86ca2e659b12fef67f266755047efbc8df,Ground News - Sudbury's hospital draw Friday w...,[geopolitics],[health_care],"[Leon Cooperman, Allianz]"

In [33]:
test_5_labeled.to_csv("silver_test_batch_5.csv", index=False)

In [35]:
#30 articles test
test_30 = label_df.sample(30, random_state=42).copy()
test_30["prompt"] = test_30["label_input"].apply(build_prompt)

print(test_30.shape)
test_30[["article_id", "title"]]

(30, 5)

,article_id,title
192,5bce820b060ef08e7f276f84c3406ec08c6311b5,Apple's New M3 Pro MacBook Pro Gets an Epic $3...
718,64983ee8c7ac596bcf012bc57e4466c160ebbc2c,Rossen Reports: Secret ways to save money at t...
168,83d8c1441e7ac5f0ca6653117311f001e18b502c,Applied Intuition Announces Favorable Resoluti...
522,2f8f94ab60b08cbb48c6a4ee55aa02b8db901de8,"Foreign investors return, stock market rebound..."
536,66f04e86ca2e659b12fef67f266755047efbc8df,Ground News - Sudbury's hospital draw Friday w...
791,9b09edeafdc1bb1ac6542e37f2ac3208d5094389,Wharton Professor Jeremy Siegel Says Stocks Co...
765,cb3d9ad151d0c44da42974845bcfd6e6c43223b4,HyperFiber Launches Green Team to Support Inst...
328,b11a31f0e2cb947f5cece113461f2b927c0901c8,Forever Cheer picks Hong Kong as gateway for g...
218,f5ef318e218c131c132bccaacf7255b6e8dd6115,Chris Martin on being environmentally friendly...
788,60b0393c5d31738af3082077a934927fd4824d9f,Guy Fieri Foundation donates $1.2M to Lahaina ...
66,9f1160ac48651487f518354d9c5c06b98bcdb536,"Taxes are on sale right now, don't miss out! S..."
640,496d5672cb67ef6acf079bee71025dceb1e22a14,L'Oreal heir becomes first woman with $100 bil...
235,d43f8d02fad14272eb0eeeeb8d6355c9fa54aa34,The digital currency platform Enet Crypto Cent...
801,fabda5ff1745b5886333713ddd26a7682980760d,chevron-right
323,980d10b2154f0b1b7c44df8259f03546b4f5ca4f,Don't Miss out on Money: Homeowners urged to c...
424,550778caf9cbcc251f538b71f177557a3e3696dc,Stock Assistant
446,2f9f2469931cde991c993720d20b0ce3e59bfe9b,3 Things To Do After The S&P 500 Gained Nearly...
109,b1f20bf019e89e7fc4cf553797895625fd622a97,AI Predictions: Meta’s Llama Says These Will B...
292,ba96d4cdb24cfd9d71e3eebfdd9390dcc81b8b69,Meiji Christmas-New Year Sale: Up to 75% Disco...
529,3c6ce204b49e0e8af831fe8d50d01fd22e08c283,Alicia Lyttle Receives Prestigious Top Artific...
139,cfb67e18466b93b85e591ef66c761d52f3e2deb2,Wendy's: One-cent Jr. Bacon Cheeseburger offer...
67,987203e46e80f93391019c1ef1fa2963b02a3eb6,Downtown Seattle Set to Score With the Opening...
368,8622c81035ebc21c5eca6e2fd6357386659d368d,Polygon MATIC Weekend Price Prediction
606,46ad29e026b80c4b203738ae579cf63f538dfd9b,L’Oreal heiress becomes first woman with $100 ...
39,b10e591e79100f130c8f28d48f1f9e7740ce3f29,Startup Fortune: Leading AI Platform DeepFakeA...
30,4b9dd92efda581d5d90ba074ec82ecb9f41d6dad,Viral photo of forlorn Spiral Hot Dogs owner l...
381,53efc1effade261c8beb52eec985b79ce04c5c4b,Cost of living crisis prompts more retailers t...
559,85478124e9a2518e95e3f276f60362c121c2d9d2,Stock Assistant
208,65cded27954c3bebaf6e5d5f01cdc048ad383257,Beyond Meat founder and CEO: The arc of histor...
78,ced676bf1e4c3ff852fd80c682f85cb104c6121f,"With EPS Growth And More, CTI Logistics (ASX:C..."

In [36]:
results_30 = []

for i, (_, row) in enumerate(test_30.iterrows(), start=1):
    print(f"Processing article {i}/30...")
    
    raw_output = call_ollama(row["prompt"])
    parsed_output = extract_json_object(raw_output)
    normalized_output = normalize_labels(parsed_output)
    
    results_30.append({
        "article_id": row["article_id"],
        "title": row["title"],
        "raw_output": raw_output,
        "macro_tags": normalized_output["macro_tags"],
        "industry_tags": normalized_output["industry_tags"],
        "entity_tags": normalized_output["entity_tags"]
    })

Processing article 1/30...
Processing article 2/30...
Processing article 3/30...
Processing article 4/30...
Processing article 5/30...
Processing article 6/30...
Processing article 7/30...
Processing article 8/30...
Processing article 9/30...
Processing article 10/30...
Processing article 11/30...
Processing article 12/30...
Processing article 13/30...
Processing article 14/30...
Processing article 15/30...
Processing article 16/30...
Processing article 17/30...
Processing article 18/30...
Processing article 19/30...
Processing article 20/30...
Processing article 21/30...
Processing article 22/30...
Processing article 23/30...
Processing article 24/30...
Processing article 25/30...
Processing article 26/30...
Processing article 27/30...
Processing article 28/30...
Processing article 29/30...
Processing article 30/30...

In [37]:
results30_df = pd.DataFrame(results_30)
results30_df

,article_id,title,raw_output,macro_tags,industry_tags,entity_tags
0,5bce820b060ef08e7f276f84c3406ec08c6311b5,Apple's New M3 Pro MacBook Pro Gets an Epic $3...,"{\n ""macro_tags"": [""consumer""],\n ""industry...",[],[technology],"[apple, bh]"
1,64983ee8c7ac596bcf012bc57e4466c160ebbc2c,Rossen Reports: Secret ways to save money at t...,"{\n ""macro_tags"": [""fx_currency""],\n ""indus...",[fx_currency],[],"[amc, cinemark, regal_cinemas, alamo_megaplex,..."
2,83d8c1441e7ac5f0ca6653117311f001e18b502c,Applied Intuition Announces Favorable Resoluti...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[technology],"[Applied Intuition, Embark Technology, Marceil..."
3,2f8f94ab60b08cbb48c6a4ee55aa02b8db901de8,"Foreign investors return, stock market rebound...","{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],"[real_estate, financials, banking]","[Vingroup, VHM, VRE, VIC, DXG, PDR, DIG, VCG, ..."
4,66f04e86ca2e659b12fef67f266755047efbc8df,Ground News - Sudbury's hospital draw Friday w...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[health_care],"[Leon Cooperman, Allianz]"
5,9b09edeafdc1bb1ac6542e37f2ac3208d5094389,Wharton Professor Jeremy Siegel Says Stocks Co...,"{\n ""macro_tags"": [""federal_reserve"", ""inter...",[interest_rates],"[financials, technology]","[Jeremy Siegel, CNBC's Closing Bell, SPDR S&P ..."
6,cb3d9ad151d0c44da42974845bcfd6e6c43223b4,HyperFiber Launches Green Team to Support Inst...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],"[technology, communication_services]",[HyperFiber]
7,b11a31f0e2cb947f5cece113461f2b927c0901c8,Forever Cheer picks Hong Kong as gateway for g...,"{\n ""macro_tags"": [""geopolitics""],\n ""indus...",[geopolitics],"[health_care, technology]","[Forever Cheer Holding, Zhuo Min, University o..."
8,f5ef318e218c131c132bccaacf7255b6e8dd6115,Chris Martin on being environmentally friendly...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[],"[chris_martin, coldplay, ellie_goulding, bbc_r..."
9,60b0393c5d31738af3082077a934927fd4824d9f,Guy Fieri Foundation donates $1.2M to Lahaina ...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[banking],"[guy_fieri, hawaii_restaurant_association, ame..."
10,9f1160ac48651487f518354d9c5c06b98bcdb536,"Taxes are on sale right now, don't miss out! S...","{\n ""macro_tags"": [""tax_cuts"", ""expiration_d...",[],[financials],[Hobart Wealth]
11,496d5672cb67ef6acf079bee71025dceb1e22a14,L'Oreal heir becomes first woman with $100 bil...,"{\n ""macro_tags"": [""fx_currency"", ""stock_mar...",[fx_currency],[],"[L'Oreal, Francoise Bettencourt Meyers, LVMH M..."
12,d43f8d02fad14272eb0eeeeb8d6355c9fa54aa34,The digital currency platform Enet Crypto Cent...,"{\n ""macro_tags"": [""blockchain""],\n ""indust...",[],"[technology, financials]",[Enet Crypto Center Limited]
13,fabda5ff1745b5886333713ddd26a7682980760d,chevron-right,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[],"[Gov. Kathy Hochul, New York State Homes and C..."
14,980d10b2154f0b1b7c44df8259f03546b4f5ca4f,Don't Miss out on Money: Homeowners urged to c...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[real_estate],"[Wisconsin_Department_of_Revenue, Catherine_Or..."
15,550778caf9cbcc251f538b71f177557a3e3696dc,Stock Assistant,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[],[aldi]
16,2f9f2469931cde991c993720d20b0ce3e59bfe9b,3 Things To Do After The S&P 500 Gained Nearly...,"{\n ""macro_tags"": [""interest_rates""],\n ""in...",[interest_rates],"[financials, technology]","[spy, snaxx, qqq, nvidia]"
17,b1f20bf019e89e7fc4cf553797895625fd622a97,AI Predictions: Meta’s Llama Says These Will B...,"{\n ""macro_tags"": [""artificial_intelligence""...",[],"[technology, financials]","[Meta, Enphase Energy]"
18,ba96d4cdb24cfd9d71e3eebfdd9390dcc81b8b69,Meiji Christmas-New Year Sale: Up to 75% Disco...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],"[technology, consumer]",[meiji]
19,3c6ce204b49e0e8af831fe8d50d01fd22e08c283,Alicia Lyttle Receives Prestigious Top Artific...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[technology],[alicia_lyttle]
20,cfb67e18466b93b85e591ef66c761d52f3e2deb2,Wendy's: One-cent Jr. Bacon Cheeseburger offer...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[consumer],[wendys]
21,987203e46e80f93391019c1ef1fa2963b02a3eb6,Downtown Seattle Set to Score With the Opening...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[consumer],"[Golden Roosters, Sean Yoon]"
22,8622c81035ebc21c5eca6e2fd6357386659d368d,Polygon MATIC Weekend Price Prediction,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[technology],"[Polygon, MATIC]"
23,46ad29e026b80c4b203738ae579cf63f538dfd9b,L’Oreal heiress becomes first woman with $100 ...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],"[consumer, technology]","[L'Oreal, Francoise Bettencourt Meyers]"
24,b10e591e79100f130c8f28d48f1f9e7740ce3f29,Startup Fortune: Leading AI Platform DeepFakeA...,"{\n ""macro_tags"": [""technology"", ""regulation...",[regulation],"[financials, technology]",[DeepFakeAI]
25,4b9dd92efda581d5d90ba074ec82ecb9f41d6dad,Viral photo of forlorn Spiral Hot Dogs owner l...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[consumer],"[Spirals: Hot Dogs & More, Scott Hosek, Nick C..."
26,53efc1effade261c8beb52eec985b79ce04c5c4b,Cost of living crisis prompts more retailers t...,"{\n ""macro_tags"": [""inflation""],\n ""industr...",[inflation],[],"[Sasha Titchkosky, Koskela]"
27,85478124e9a2518e95e3f276f60362c121c2d9d2,Stock Assistant,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[],[aldi]
28,65cded27954c3bebaf6e5d5f01cdc048ad383257,Beyond Meat founder and CEO: The arc of histor...,"{\n ""macro_tags"": [""geopolitics""],\n ""indus...",[geopolitics],"[consumer, technology]","[Beyond Meat, Ethan Brown, Yahoo Finance's Lea..."
29,ced676bf1e4c3ff852fd80c682f85cb104c6121f,"With EPS Growth And More, CTI Logistics (ASX:C...","{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[financials],"[CTI Logistics, ASX:CLX]"

In [38]:
test_30_labeled = test_30.merge(
    results30_df[["article_id", "macro_tags", "industry_tags", "entity_tags"]],
    on="article_id",
    how="left"
)

test_30_labeled[["article_id", "title", "macro_tags", "industry_tags", "entity_tags"]]

,article_id,title,macro_tags,industry_tags,entity_tags
0,5bce820b060ef08e7f276f84c3406ec08c6311b5,Apple's New M3 Pro MacBook Pro Gets an Epic $3...,[],[technology],"[apple, bh]"
1,64983ee8c7ac596bcf012bc57e4466c160ebbc2c,Rossen Reports: Secret ways to save money at t...,[fx_currency],[],"[amc, cinemark, regal_cinemas, alamo_megaplex,..."
2,83d8c1441e7ac5f0ca6653117311f001e18b502c,Applied Intuition Announces Favorable Resoluti...,[],[technology],"[Applied Intuition, Embark Technology, Marceil..."
3,2f8f94ab60b08cbb48c6a4ee55aa02b8db901de8,"Foreign investors return, stock market rebound...",[],"[real_estate, financials, banking]","[Vingroup, VHM, VRE, VIC, DXG, PDR, DIG, VCG, ..."
4,66f04e86ca2e659b12fef67f266755047efbc8df,Ground News - Sudbury's hospital draw Friday w...,[],[health_care],"[Leon Cooperman, Allianz]"
5,9b09edeafdc1bb1ac6542e37f2ac3208d5094389,Wharton Professor Jeremy Siegel Says Stocks Co...,[interest_rates],"[financials, technology]","[Jeremy Siegel, CNBC's Closing Bell, SPDR S&P ..."
6,cb3d9ad151d0c44da42974845bcfd6e6c43223b4,HyperFiber Launches Green Team to Support Inst...,[],"[technology, communication_services]",[HyperFiber]
7,b11a31f0e2cb947f5cece113461f2b927c0901c8,Forever Cheer picks Hong Kong as gateway for g...,[geopolitics],"[health_care, technology]","[Forever Cheer Holding, Zhuo Min, University o..."
8,f5ef318e218c131c132bccaacf7255b6e8dd6115,Chris Martin on being environmentally friendly...,[],[],"[chris_martin, coldplay, ellie_goulding, bbc_r..."
9,60b0393c5d31738af3082077a934927fd4824d9f,Guy Fieri Foundation donates $1.2M to Lahaina ...,[],[banking],"[guy_fieri, hawaii_restaurant_association, ame..."
10,9f1160ac48651487f518354d9c5c06b98bcdb536,"Taxes are on sale right now, don't miss out! S...",[],[financials],[Hobart Wealth]
11,496d5672cb67ef6acf079bee71025dceb1e22a14,L'Oreal heir becomes first woman with $100 bil...,[fx_currency],[],"[L'Oreal, Francoise Bettencourt Meyers, LVMH M..."
12,d43f8d02fad14272eb0eeeeb8d6355c9fa54aa34,The digital currency platform Enet Crypto Cent...,[],"[technology, financials]",[Enet Crypto Center Limited]
13,fabda5ff1745b5886333713ddd26a7682980760d,chevron-right,[],[],"[Gov. Kathy Hochul, New York State Homes and C..."
14,980d10b2154f0b1b7c44df8259f03546b4f5ca4f,Don't Miss out on Money: Homeowners urged to c...,[],[real_estate],"[Wisconsin_Department_of_Revenue, Catherine_Or..."
15,550778caf9cbcc251f538b71f177557a3e3696dc,Stock Assistant,[],[],[aldi]
16,2f9f2469931cde991c993720d20b0ce3e59bfe9b,3 Things To Do After The S&P 500 Gained Nearly...,[interest_rates],"[financials, technology]","[spy, snaxx, qqq, nvidia]"
17,b1f20bf019e89e7fc4cf553797895625fd622a97,AI Predictions: Meta’s Llama Says These Will B...,[],"[technology, financials]","[Meta, Enphase Energy]"
18,ba96d4cdb24cfd9d71e3eebfdd9390dcc81b8b69,Meiji Christmas-New Year Sale: Up to 75% Disco...,[],"[technology, consumer]",[meiji]
19,3c6ce204b49e0e8af831fe8d50d01fd22e08c283,Alicia Lyttle Receives Prestigious Top Artific...,[],[technology],[alicia_lyttle]
20,cfb67e18466b93b85e591ef66c761d52f3e2deb2,Wendy's: One-cent Jr. Bacon Cheeseburger offer...,[],[consumer],[wendys]
21,987203e46e80f93391019c1ef1fa2963b02a3eb6,Downtown Seattle Set to Score With the Opening...,[],[consumer],"[Golden Roosters, Sean Yoon]"
22,8622c81035ebc21c5eca6e2fd6357386659d368d,Polygon MATIC Weekend Price Prediction,[],[technology],"[Polygon, MATIC]"
23,46ad29e026b80c4b203738ae579cf63f538dfd9b,L’Oreal heiress becomes first woman with $100 ...,[],"[consumer, technology]","[L'Oreal, Francoise Bettencourt Meyers]"
24,b10e591e79100f130c8f28d48f1f9e7740ce3f29,Startup Fortune: Leading AI Platform DeepFakeA...,[regulation],"[financials, technology]",[DeepFakeAI]
25,4b9dd92efda581d5d90ba074ec82ecb9f41d6dad,Viral photo of forlorn Spiral Hot Dogs owner l...,[],[consumer],"[Spirals: Hot Dogs & More, Scott Hosek, Nick C..."
26,53efc1effade261c8beb52eec985b79ce04c5c4b,Cost of living crisis prompts more retailers t...,[inflation],[],"[Sasha Titchkosky, Koskela]"
27,85478124e9a2518e95e3f276f60362c121c2d9d2,Stock Assistant,[],[],[aldi]
28,65cded27954c3bebaf6e5d5f01cdc048ad383257,Beyond Meat founder and CEO: The arc of histor...,[geopolitics],"[consumer, technology]","[Beyond Meat, Ethan Brown, Yahoo Finance's Lea..."
29,ced676bf1e4c3ff852fd80c682f85cb104c6121f,"With EPS Growth And More, CTI Logistics (ASX:C...",[],[financials],"[CTI Logistics, ASX:CLX]"

In [39]:
test_30_labeled.to_csv("silver_test_batch_30.csv", index=False)

In [40]:
#50 articles test
test_50 = label_df.sample(50, random_state=42).copy()
test_50["prompt"] = test_50["label_input"].apply(build_prompt)

print(test_50.shape)
test_50[["article_id", "title"]]

(50, 5)

,article_id,title
192,5bce820b060ef08e7f276f84c3406ec08c6311b5,Apple's New M3 Pro MacBook Pro Gets an Epic $3...
718,64983ee8c7ac596bcf012bc57e4466c160ebbc2c,Rossen Reports: Secret ways to save money at t...
168,83d8c1441e7ac5f0ca6653117311f001e18b502c,Applied Intuition Announces Favorable Resoluti...
522,2f8f94ab60b08cbb48c6a4ee55aa02b8db901de8,"Foreign investors return, stock market rebound..."
536,66f04e86ca2e659b12fef67f266755047efbc8df,Ground News - Sudbury's hospital draw Friday w...
791,9b09edeafdc1bb1ac6542e37f2ac3208d5094389,Wharton Professor Jeremy Siegel Says Stocks Co...
765,cb3d9ad151d0c44da42974845bcfd6e6c43223b4,HyperFiber Launches Green Team to Support Inst...
328,b11a31f0e2cb947f5cece113461f2b927c0901c8,Forever Cheer picks Hong Kong as gateway for g...
218,f5ef318e218c131c132bccaacf7255b6e8dd6115,Chris Martin on being environmentally friendly...
788,60b0393c5d31738af3082077a934927fd4824d9f,Guy Fieri Foundation donates $1.2M to Lahaina ...
66,9f1160ac48651487f518354d9c5c06b98bcdb536,"Taxes are on sale right now, don't miss out! S..."
640,496d5672cb67ef6acf079bee71025dceb1e22a14,L'Oreal heir becomes first woman with $100 bil...
235,d43f8d02fad14272eb0eeeeb8d6355c9fa54aa34,The digital currency platform Enet Crypto Cent...
801,fabda5ff1745b5886333713ddd26a7682980760d,chevron-right
323,980d10b2154f0b1b7c44df8259f03546b4f5ca4f,Don't Miss out on Money: Homeowners urged to c...
424,550778caf9cbcc251f538b71f177557a3e3696dc,Stock Assistant
446,2f9f2469931cde991c993720d20b0ce3e59bfe9b,3 Things To Do After The S&P 500 Gained Nearly...
109,b1f20bf019e89e7fc4cf553797895625fd622a97,AI Predictions: Meta’s Llama Says These Will B...
292,ba96d4cdb24cfd9d71e3eebfdd9390dcc81b8b69,Meiji Christmas-New Year Sale: Up to 75% Disco...
529,3c6ce204b49e0e8af831fe8d50d01fd22e08c283,Alicia Lyttle Receives Prestigious Top Artific...
139,cfb67e18466b93b85e591ef66c761d52f3e2deb2,Wendy's: One-cent Jr. Bacon Cheeseburger offer...
67,987203e46e80f93391019c1ef1fa2963b02a3eb6,Downtown Seattle Set to Score With the Opening...
368,8622c81035ebc21c5eca6e2fd6357386659d368d,Polygon MATIC Weekend Price Prediction
606,46ad29e026b80c4b203738ae579cf63f538dfd9b,L’Oreal heiress becomes first woman with $100 ...
39,b10e591e79100f130c8f28d48f1f9e7740ce3f29,Startup Fortune: Leading AI Platform DeepFakeA...
30,4b9dd92efda581d5d90ba074ec82ecb9f41d6dad,Viral photo of forlorn Spiral Hot Dogs owner l...
381,53efc1effade261c8beb52eec985b79ce04c5c4b,Cost of living crisis prompts more retailers t...
559,85478124e9a2518e95e3f276f60362c121c2d9d2,Stock Assistant
208,65cded27954c3bebaf6e5d5f01cdc048ad383257,Beyond Meat founder and CEO: The arc of histor...
78,ced676bf1e4c3ff852fd80c682f85cb104c6121f,"With EPS Growth And More, CTI Logistics (ASX:C..."
728,0a9719146309f2c7a4bae1129018e2ab0099309f,Stanislav Kondrashov Telf AG: on the prospects...
440,8ae5b61eaecd706873438c460d38b349da6ad319,Oxbridge Notes Invites New Authors to Join Its...
174,9ab1f2406e01ca9d0ed3c62441eaf627bc94dbf7,hoggo Pioneers Vision for Transparent Data Pri...
332,0bf685038b318d02174e2c73ed2940990a1353f5,Emerging markets are looking attractive after ...
719,892298221de74df38fd67d054fcc36fdf45a9d51,"TYB rewards golf caddies, course workers for c..."
23,1369530d612c9fb04c7168f20f7a4fede9b47bb6,Mergers and Acquisitions Fuel Aussie Miners' S...
598,feb360ce3b85bf9cf80d69ca7cf51ea33cb186d8,Grayscale CEO Foresees Bitcoin Price Surging t...
394,28505ccf025103c0c6d90c9d0e7b18cb4039c508,Americans cross the U.S.-Mexico border for mor...
63,4c143ff57ec0e565de01d53ce55fac68c702e106,The Web design company Diaries
335,d1de65bf4fcccdeaa61fa0fe7e393ccb26b868f4,Tackling your New Year's resolution with money...
65,8cc0ebc18c60296dd7869022d8fb3d7c3184c870,New Illinois law mandates paid time off for wo...
660,612b702fedf70ff6fd5986ba7b107c176219d5ef,Amina Stevens Talks OWNership Tips She’s Shari...
655,46d85557a2ab5589ddce0c8bea8a738794f0f7b4,"In Moscow to meet Putin and Lavrov, India’s fo..."
137,25d97efe3813078d70a81fbda811d7770b493143,Choicese (CHC-SES) Drives Financial Digitizati...
597,3ea09c783e77873d7164af0e770493613346c19f,11 Frugal Habits To Adopt If You’re Single and...
210,020186950b7db6cb6e9fb6d8e3efab97ee732ae6,Thierry Henry hails Arsenal transfer target Do...
528,754210a884d3035a9d6ef1954f9fcaaa1d8867ea,10 compact under-desk treadmills to increase y...
388,fe9184a2b5b1424d99fa046879c6d6de61494203,Iowans get an income tax break in 2024
395,9b9b42d9ff8847d3e97e2b5b879c2dcc23a74be8,The digital currency platform Enet Crypto Cent...
568,9ecb41dd5ca5e2a29c1272a22f6ce565a1644b18,I Found 8 Bestselling Amazon Winter Jackets on...

In [41]:
results_50 = []

for i, (_, row) in enumerate(test_50.iterrows(), start=1):
    print(f"Processing article {i}/50...")
    
    raw_output = call_ollama(row["prompt"])
    parsed_output = extract_json_object(raw_output)
    normalized_output = normalize_labels(parsed_output)
    
    results_50.append({
        "article_id": row["article_id"],
        "title": row["title"],
        "raw_output": raw_output,
        "macro_tags": normalized_output["macro_tags"],
        "industry_tags": normalized_output["industry_tags"],
        "entity_tags": normalized_output["entity_tags"]
    })

Processing article 1/50...
Processing article 2/50...
Processing article 3/50...
Processing article 4/50...
Processing article 5/50...
Processing article 6/50...
Processing article 7/50...
Processing article 8/50...
Processing article 9/50...
Processing article 10/50...
Processing article 11/50...
Processing article 12/50...
Processing article 13/50...
Processing article 14/50...
Processing article 15/50...
Processing article 16/50...
Processing article 17/50...
Processing article 18/50...
Processing article 19/50...
Processing article 20/50...
Processing article 21/50...
Processing article 22/50...
Processing article 23/50...
Processing article 24/50...
Processing article 25/50...
Processing article 26/50...
Processing article 27/50...
Processing article 28/50...
Processing article 29/50...
Processing article 30/50...
Processing article 31/50...
Processing article 32/50...
Processing article 33/50...
Processing article 34/50...
Processing article 35/50...
Processing article 36/50...
Processing article 37/50...
Processing article 38/50...
Processing article 39/50...
Processing article 40/50...
Processing article 41/50...
Processing article 42/50...
Processing article 43/50...
Processing article 44/50...
Processing article 45/50...
Processing article 46/50...
Processing article 47/50...
Processing article 48/50...
Processing article 49/50...
Processing article 50/50...

In [42]:
results50_df = pd.DataFrame(results_50)
results50_df

,article_id,title,raw_output,macro_tags,industry_tags,entity_tags
0,5bce820b060ef08e7f276f84c3406ec08c6311b5,Apple's New M3 Pro MacBook Pro Gets an Epic $3...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[technology],"[apple, B&H]"
1,64983ee8c7ac596bcf012bc57e4466c160ebbc2c,Rossen Reports: Secret ways to save money at t...,"{\n ""macro_tags"": [""inflation""],\n ""industr...",[inflation],[],"[amc, cinemark, regal_cinemas, aaa]"
2,83d8c1441e7ac5f0ca6653117311f001e18b502c,Applied Intuition Announces Favorable Resoluti...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[technology],"[applied_intuition, embank_technology]"
3,2f8f94ab60b08cbb48c6a4ee55aa02b8db901de8,"Foreign investors return, stock market rebound...","{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],"[real_estate, financials, banking]","[Vingroup, VHM, VRE, VIC, DXG, PDR, DIG, VCG, ..."
4,66f04e86ca2e659b12fef67f266755047efbc8df,Ground News - Sudbury's hospital draw Friday w...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[health_care],"[Leon Cooperman, Allianz]"
5,9b09edeafdc1bb1ac6542e37f2ac3208d5094389,Wharton Professor Jeremy Siegel Says Stocks Co...,"{\n ""macro_tags"": [""fiscal_policy"", ""interes...","[fiscal_policy, interest_rates]",[financials],"[Jeremy Siegel, Federal Reserve, SPDR S&P 500 ..."
6,cb3d9ad151d0c44da42974845bcfd6e6c43223b4,HyperFiber Launches Green Team to Support Inst...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],"[technology, communication_services]",[HyperFiber]
7,b11a31f0e2cb947f5cece113461f2b927c0901c8,Forever Cheer picks Hong Kong as gateway for g...,"{\n ""macro_tags"": [""geopolitics""],\n ""indus...",[geopolitics],"[health_care, technology]","[Forever Cheer Holding, Zhuo Min, University o..."
8,f5ef318e218c131c132bccaacf7255b6e8dd6115,Chris Martin on being environmentally friendly...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[],"[chris_martin, coldplay, ellie_goulding, bbc_r..."
9,60b0393c5d31738af3082077a934927fd4824d9f,Guy Fieri Foundation donates $1.2M to Lahaina ...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[banking],"[guy_fieri, hawaii_restaurant_association, ame..."
10,9f1160ac48651487f518354d9c5c06b98bcdb536,"Taxes are on sale right now, don't miss out! S...","{\n ""macro_tags"": [""taxes"", ""2017_tax_cuts_a...",[],"[financials, banking]",[Hobart Wealth]
11,496d5672cb67ef6acf079bee71025dceb1e22a14,L'Oreal heir becomes first woman with $100 bil...,"{\n ""macro_tags"": [""fx_currency""],\n ""indus...",[fx_currency],"[financials, technology, consumer, health_care]","[L'Oreal, Francoise Bettencourt Meyers, LVMH M..."
12,d43f8d02fad14272eb0eeeeb8d6355c9fa54aa34,The digital currency platform Enet Crypto Cent...,"{\n ""macro_tags"": [""blockchain""],\n ""indust...",[],[technology],[Enet Crypto Center Limited]
13,fabda5ff1745b5886333713ddd26a7682980760d,chevron-right,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[],"[Gov. Kathy Hochul, New York State Homes and C..."
14,980d10b2154f0b1b7c44df8259f03546b4f5ca4f,Don't Miss out on Money: Homeowners urged to c...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[real_estate],"[wisconsin_department_of_revenue, catherine_or..."
15,550778caf9cbcc251f538b71f177557a3e3696dc,Stock Assistant,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[],[aldi]
16,2f9f2469931cde991c993720d20b0ce3e59bfe9b,3 Things To Do After The S&P 500 Gained Nearly...,"{\n ""macro_tags"": [""interest_rates""],\n ""in...",[interest_rates],"[technology, financials]","[SPY, SNAXX, QQQ, NVDA]"
17,b1f20bf019e89e7fc4cf553797895625fd622a97,AI Predictions: Meta’s Llama Says These Will B...,"{\n ""macro_tags"": [""fx_currency"", ""commoditi...","[fx_currency, commodities]","[technology, energy]","[Meta, Enphase_Energy]"
18,ba96d4cdb24cfd9d71e3eebfdd9390dcc81b8b69,Meiji Christmas-New Year Sale: Up to 75% Disco...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],"[technology, consumer]",[meiji]
19,3c6ce204b49e0e8af831fe8d50d01fd22e08c283,Alicia Lyttle Receives Prestigious Top Artific...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[technology],[Alicia Lyttle]
20,cfb67e18466b93b85e591ef66c761d52f3e2deb2,Wendy's: One-cent Jr. Bacon Cheeseburger offer...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[consumer],[wendys]
21,987203e46e80f93391019c1ef1fa2963b02a3eb6,Downtown Seattle Set to Score With the Opening...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[real_estate],"[Golden Roosters, Sean Yoon, What Now Seattle]"
22,8622c81035ebc21c5eca6e2fd6357386659d368d,Polygon MATIC Weekend Price Prediction,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[technology],"[Polygon, MATIC, Sandeep Nailwal]"
23,46ad29e026b80c4b203738ae579cf63f538dfd9b,L’Oreal heiress becomes first woman with $100 ...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],"[consumer, technology]","[L'Oreal, Francoise Bettencourt Meyers, Lilian..."
24,b10e591e79100f130c8f28d48f1f9e7740ce3f29,Startup Fortune: Leading AI Platform DeepFakeA...,"{\n ""macro_tags"": [""technology""],\n ""indust...",[],[financials],[DeepFakeAI]
25,4b9dd92efda581d5d90ba074ec82ecb9f41d6dad,Viral photo of forlorn Spiral Hot Dogs owner l...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[consumer],"[Spirals: Hot Dogs & More, Scott Hosek, Nick C..."
26,53efc1effade261c8beb52eec985b79ce04c5c4b,Cost of living crisis prompts more retailers t...,"{\n ""macro_tags"": [""inflation""],\n ""industr...",[inflation],[],"[Sasha Titchkosky, Koskela]"
27,85478124e9a2518e95e3f276f60362c121c2d9d2,Stock Assistant,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[],[aldi]
28,65cded27954c3bebaf6e5d5f01cdc048ad383257,Beyond Meat founder and CEO: The arc of histor...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],"[consumer, technology]","[Beyond Meat, Ethan Brown]"
29,ced676bf1e4c3ff852fd80c682f85cb104c6121f,"With EPS Growth And More, CTI Logistics (ASX:C...","{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[financials],"[CTI Logistics, Simply Wall St]"
30,0a9719146309f2c7a4bae1129018e2ab0099309f,Stanislav Kondrashov Telf AG: on the prospects...,"{\n ""macro_tags"": [""fx_currency"", ""geopoliti...","[fx_currency, geopolitics]",[financials],"[Stanislav Kondrashov, Telf AG]"
31,8ae5b61eaecd706873438c460d38b349da6ad319,Oxbridge Notes Invites New Authors to Join Its...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[],[Oxbridge Notes]
32,9ab1f2406e01ca9d0ed3c62441eaf627bc94dbf7,hoggo Pioneers Vision for Transparent Data Pri...,"{\n ""macro_tags"": [""geopolitics""],\n ""indus...",[geopolitics],"[technology, financials]","[hoggo, samuel_solberg, noa_kahalon, toni_stje..."
33,0bf685038b318d02174e2c73ed2940990a1353f5,Emerging markets are looking attractive after ...,"{\n ""macro_tags"": [""personal_finance"", ""cred...",[],[banking],"[JPMorgan, Joyce Chang]"
34,892298221de74df38fd67d054fcc36fdf45a9d51,"TYB rewards golf caddies, course workers for c...","{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[real_estate],[tyb_international_golf_resort_and_country_clu...
35,1369530d612c9fb04c7168f20f7a4fede9b47bb6,Mergers and Acquisitions Fuel Aussie Miners' S...,"{\n ""macro_tags"": [""commodities"", ""geopoliti...","[commodities, geopolitics]",[technology],"[xmm, bhp, rio, fmg, fortescue, whitehaven, igO]"
36,feb360ce3b85bf9cf80d69ca7cf51ea33cb186d8,Grayscale CEO Foresees Bitcoin Price Surging t...,"{\n ""macro_tags"": [""crypto_market"", ""global_...",[],"[technology, financials]","[grayscale, us_securities_and_exchange_commiss..."
37,28505ccf025103c0c6d90c9d0e7b18cb4039c508,Americans cross the U.S.-Mexico border for mor...,"{\n ""macro_tags"": [""geopolitics""],\n ""indus...",[geopolitics],[health_care],"[cristina_yanez, alex, dr_ciguena]"
38,4c143ff57ec0e565de01d53ce55fac68c702e106,The Web design company Diaries,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[technology],"[Amazon, Rise Interactive, diaries]"
39,d1de65bf4fcccdeaa61fa0fe7e393ccb26b868f4,Tackling your New Year's resolution with money...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[consumer],"[dealnews.com, julie_ramhold]"
40,8cc0ebc18c60296dd7869022d8fb3d7c3184c870,New Illinois law mandates paid time off for wo...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[financials],"[Illinois, JB Pritzker, Jehan Gordon-Booth, Ki..."
41,612b702fedf70ff6fd5986ba7b107c176219d5ef,Amina Stevens Talks OWNership Tips She’s Shari...,"{\n ""macro_tags"": [""housing_disparity"", ""ret...",[],[real_estate],"[Amina_Stevens, Loretta]"
42,46d85557a2ab5589ddce0c8bea8a738794f0f7b4,"In Moscow to meet Putin and Lavrov, India’s fo...","{\n ""macro_tags"": [""geopolitics""],\n ""indus...",[geopolitics],"[energy, consumer]","[vladimir_putin, subrahmanyam_jaishankar, serg..."
43,25d97efe3813078d70a81fbda811d7770b493143,Choicese (CHC-SES) Drives Financial Digitizati...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],"[financials, technology]","[Choicese, CHC-SES, leading brokerage firm]"
44,3ea09c783e77873d7164af0e770493613346c19f,11 Frugal Habits To Adopt If You’re Single and...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[consumer],[Suze Orman]
45,020186950b7db6cb6e9fb6d8e3efab97ee732ae6,Thierry Henry hails Arsenal transfer target Do...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[],"[thierry_henry, dominic_solanke, afc_bournemouth]"
46,754210a884d3035a9d6ef1954f9fcaaa1d8867ea,10 compact under-desk treadmills to increase y...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[technology],[good_morning_america]
47,fe9184a2b5b1424d99fa046879c6d6de61494203,Iowans get an income tax break in 2024,"{\n ""macro_tags"": [""fiscal_policy"", ""recessi...","[fiscal_policy, recession_growth]","[financials, banking]","[Kim Reynolds, Revenue Estimating Conference, ..."
48,9b9b42d9ff8847d3e97e2b5b879c2dcc23a74be8,The digital currency platform Enet Crypto Cent...,"{\n ""macro_tags"": [""fincen"", ""regulation""],\...",[regulation],"[technology, financials]","[Enet Crypto Center Limited, Enet Exchange]"
49,9ecb41dd5ca5e2a29c1272a22f6ce565a1644b18,I Found 8 Bestselling Amazon Winter Jackets on...,"{\n ""macro_tags"": [],\n ""industry_tags"": [""...",[],[technology],[amazon]

In [43]:
test_50_labeled = test_50.merge(
    results50_df[["article_id", "macro_tags", "industry_tags", "entity_tags"]],
    on="article_id",
    how="left"
)

test_50_labeled[["article_id", "title", "macro_tags", "industry_tags", "entity_tags"]]

,article_id,title,macro_tags,industry_tags,entity_tags
0,5bce820b060ef08e7f276f84c3406ec08c6311b5,Apple's New M3 Pro MacBook Pro Gets an Epic $3...,[],[technology],"[apple, B&H]"
1,64983ee8c7ac596bcf012bc57e4466c160ebbc2c,Rossen Reports: Secret ways to save money at t...,[inflation],[],"[amc, cinemark, regal_cinemas, aaa]"
2,83d8c1441e7ac5f0ca6653117311f001e18b502c,Applied Intuition Announces Favorable Resoluti...,[],[technology],"[applied_intuition, embank_technology]"
3,2f8f94ab60b08cbb48c6a4ee55aa02b8db901de8,"Foreign investors return, stock market rebound...",[],"[real_estate, financials, banking]","[Vingroup, VHM, VRE, VIC, DXG, PDR, DIG, VCG, ..."
4,66f04e86ca2e659b12fef67f266755047efbc8df,Ground News - Sudbury's hospital draw Friday w...,[],[health_care],"[Leon Cooperman, Allianz]"
5,9b09edeafdc1bb1ac6542e37f2ac3208d5094389,Wharton Professor Jeremy Siegel Says Stocks Co...,"[fiscal_policy, interest_rates]",[financials],"[Jeremy Siegel, Federal Reserve, SPDR S&P 500 ..."
6,cb3d9ad151d0c44da42974845bcfd6e6c43223b4,HyperFiber Launches Green Team to Support Inst...,[],"[technology, communication_services]",[HyperFiber]
7,b11a31f0e2cb947f5cece113461f2b927c0901c8,Forever Cheer picks Hong Kong as gateway for g...,[geopolitics],"[health_care, technology]","[Forever Cheer Holding, Zhuo Min, University o..."
8,f5ef318e218c131c132bccaacf7255b6e8dd6115,Chris Martin on being environmentally friendly...,[],[],"[chris_martin, coldplay, ellie_goulding, bbc_r..."
9,60b0393c5d31738af3082077a934927fd4824d9f,Guy Fieri Foundation donates $1.2M to Lahaina ...,[],[banking],"[guy_fieri, hawaii_restaurant_association, ame..."
10,9f1160ac48651487f518354d9c5c06b98bcdb536,"Taxes are on sale right now, don't miss out! S...",[],"[financials, banking]",[Hobart Wealth]
11,496d5672cb67ef6acf079bee71025dceb1e22a14,L'Oreal heir becomes first woman with $100 bil...,[fx_currency],"[financials, technology, consumer, health_care]","[L'Oreal, Francoise Bettencourt Meyers, LVMH M..."
12,d43f8d02fad14272eb0eeeeb8d6355c9fa54aa34,The digital currency platform Enet Crypto Cent...,[],[technology],[Enet Crypto Center Limited]
13,fabda5ff1745b5886333713ddd26a7682980760d,chevron-right,[],[],"[Gov. Kathy Hochul, New York State Homes and C..."
14,980d10b2154f0b1b7c44df8259f03546b4f5ca4f,Don't Miss out on Money: Homeowners urged to c...,[],[real_estate],"[wisconsin_department_of_revenue, catherine_or..."
15,550778caf9cbcc251f538b71f177557a3e3696dc,Stock Assistant,[],[],[aldi]
16,2f9f2469931cde991c993720d20b0ce3e59bfe9b,3 Things To Do After The S&P 500 Gained Nearly...,[interest_rates],"[technology, financials]","[SPY, SNAXX, QQQ, NVDA]"
17,b1f20bf019e89e7fc4cf553797895625fd622a97,AI Predictions: Meta’s Llama Says These Will B...,"[fx_currency, commodities]","[technology, energy]","[Meta, Enphase_Energy]"
18,ba96d4cdb24cfd9d71e3eebfdd9390dcc81b8b69,Meiji Christmas-New Year Sale: Up to 75% Disco...,[],"[technology, consumer]",[meiji]
19,3c6ce204b49e0e8af831fe8d50d01fd22e08c283,Alicia Lyttle Receives Prestigious Top Artific...,[],[technology],[Alicia Lyttle]
20,cfb67e18466b93b85e591ef66c761d52f3e2deb2,Wendy's: One-cent Jr. Bacon Cheeseburger offer...,[],[consumer],[wendys]
21,987203e46e80f93391019c1ef1fa2963b02a3eb6,Downtown Seattle Set to Score With the Opening...,[],[real_estate],"[Golden Roosters, Sean Yoon, What Now Seattle]"
22,8622c81035ebc21c5eca6e2fd6357386659d368d,Polygon MATIC Weekend Price Prediction,[],[technology],"[Polygon, MATIC, Sandeep Nailwal]"
23,46ad29e026b80c4b203738ae579cf63f538dfd9b,L’Oreal heiress becomes first woman with $100 ...,[],"[consumer, technology]","[L'Oreal, Francoise Bettencourt Meyers, Lilian..."
24,b10e591e79100f130c8f28d48f1f9e7740ce3f29,Startup Fortune: Leading AI Platform DeepFakeA...,[],[financials],[DeepFakeAI]
25,4b9dd92efda581d5d90ba074ec82ecb9f41d6dad,Viral photo of forlorn Spiral Hot Dogs owner l...,[],[consumer],"[Spirals: Hot Dogs & More, Scott Hosek, Nick C..."
26,53efc1effade261c8beb52eec985b79ce04c5c4b,Cost of living crisis prompts more retailers t...,[inflation],[],"[Sasha Titchkosky, Koskela]"
27,85478124e9a2518e95e3f276f60362c121c2d9d2,Stock Assistant,[],[],[aldi]
28,65cded27954c3bebaf6e5d5f01cdc048ad383257,Beyond Meat founder and CEO: The arc of histor...,[],"[consumer, technology]","[Beyond Meat, Ethan Brown]"
29,ced676bf1e4c3ff852fd80c682f85cb104c6121f,"With EPS Growth And More, CTI Logistics (ASX:C...",[],[financials],"[CTI Logistics, Simply Wall St]"
30,0a9719146309f2c7a4bae1129018e2ab0099309f,Stanislav Kondrashov Telf AG: on the prospects...,"[fx_currency, geopolitics]",[financials],"[Stanislav Kondrashov, Telf AG]"
31,8ae5b61eaecd706873438c460d38b349da6ad319,Oxbridge Notes Invites New Authors to Join Its...,[],[],[Oxbridge Notes]
32,9ab1f2406e01ca9d0ed3c62441eaf627bc94dbf7,hoggo Pioneers Vision for Transparent Data Pri...,[geopolitics],"[technology, financials]","[hoggo, samuel_solberg, noa_kahalon, toni_stje..."
33,0bf685038b318d02174e2c73ed2940990a1353f5,Emerging markets are looking attractive after ...,[],[banking],"[JPMorgan, Joyce Chang]"
34,892298221de74df38fd67d054fcc36fdf45a9d51,"TYB rewards golf caddies, course workers for c...",[],[real_estate],[tyb_international_golf_resort_and_country_clu...
35,1369530d612c9fb04c7168f20f7a4fede9b47bb6,Mergers and Acquisitions Fuel Aussie Miners' S...,"[commodities, geopolitics]",[technology],"[xmm, bhp, rio, fmg, fortescue, whitehaven, igO]"
36,feb360ce3b85bf9cf80d69ca7cf51ea33cb186d8,Grayscale CEO Foresees Bitcoin Price Surging t...,[],"[technology, financials]","[grayscale, us_securities_and_exchange_commiss..."
37,28505ccf025103c0c6d90c9d0e7b18cb4039c508,Americans cross the U.S.-Mexico border for mor...,[geopolitics],[health_care],"[cristina_yanez, alex, dr_ciguena]"
38,4c143ff57ec0e565de01d53ce55fac68c702e106,The Web design company Diaries,[],[technology],"[Amazon, Rise Interactive, diaries]"
39,d1de65bf4fcccdeaa61fa0fe7e393ccb26b868f4,Tackling your New Year's resolution with money...,[],[consumer],"[dealnews.com, julie_ramhold]"
40,8cc0ebc18c60296dd7869022d8fb3d7c3184c870,New Illinois law mandates paid time off for wo...,[],[financials],"[Illinois, JB Pritzker, Jehan Gordon-Booth, Ki..."
41,612b702fedf70ff6fd5986ba7b107c176219d5ef,Amina Stevens Talks OWNership Tips She’s Shari...,[],[real_estate],"[Amina_Stevens, Loretta]"
42,46d85557a2ab5589ddce0c8bea8a738794f0f7b4,"In Moscow to meet Putin and Lavrov, India’s fo...",[geopolitics],"[energy, consumer]","[vladimir_putin, subrahmanyam_jaishankar, serg..."
43,25d97efe3813078d70a81fbda811d7770b493143,Choicese (CHC-SES) Drives Financial Digitizati...,[],"[financials, technology]","[Choicese, CHC-SES, leading brokerage firm]"
44,3ea09c783e77873d7164af0e770493613346c19f,11 Frugal Habits To Adopt If You’re Single and...,[],[consumer],[Suze Orman]
45,020186950b7db6cb6e9fb6d8e3efab97ee732ae6,Thierry Henry hails Arsenal transfer target Do...,[],[],"[thierry_henry, dominic_solanke, afc_bournemouth]"
46,754210a884d3035a9d6ef1954f9fcaaa1d8867ea,10 compact under-desk treadmills to increase y...,[],[technology],[good_morning_america]
47,fe9184a2b5b1424d99fa046879c6d6de61494203,Iowans get an income tax break in 2024,"[fiscal_policy, recession_growth]","[financials, banking]","[Kim Reynolds, Revenue Estimating Conference, ..."
48,9b9b42d9ff8847d3e97e2b5b879c2dcc23a74be8,The digital currency platform Enet Crypto Cent...,[regulation],"[technology, financials]","[Enet Crypto Center Limited, Enet Exchange]"
49,9ecb41dd5ca5e2a29c1272a22f6ce565a1644b18,I Found 8 Bestselling Amazon Winter Jackets on...,[],[technology],[amazon]

In [44]:
test_50_labeled.to_csv("silver_test_batch_50.csv", index=False)